name: 🐞 Report a Bug
description: Report a bug/issue
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: checkboxes
  attributes:
    label: Have you installed the latest version of nfl_data_py?
    description: Use `pip install --upgrade nfl_data_py`.
    options:
    - label: I have installed the latest version of nfl_data_py. 
      required: true

- type: dropdown
  attributes:
    label: If this is a play-by-play data issue, are you using the cache feature?
    description: Run `import_pbp_data()` with `cache=False` if using caching.
    options:
      - I have run with `cache=False` and the issue persists.
      - This is not a play-by-play data issue.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: Example
    render: python
    description: | 
      Please provide a short, reproducible example of the code you're trying to run.
      Include import statements and minimal code that demonstrates the issue.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true